name: Generate Directory Listing
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: node /home/runner/work/tfmsa/tfmsa/generate-file-listing.js
      - run: git config user.name "bot" && git commit -am "Update listing" && git push || true
